version: '3'
services:
  nginx:
    container_name: hexo-blog-nginx
    build: .
    image: hexo-blog-nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nginx
    volumes:
      - nginx:/etc/nginx/conf.d
volumes:
  nginx:
networks:
  nginx:
