version: '3'
services:
  nginx:
    container_name: hexo-blog
    build:
      context: .
    networks:
      - nginx
    volumes:
      - nginx:/etc/nginx/conf.d
volumes:
  nginx:
networks:
  nginx:
