version: '3'
services:
  blog:
    container_name: hexo-blog
    build: .
    image: hexo-blog
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginx-conf:/etc/nginx/conf.d
volumes:
  nginx-conf:
